-- PMMS / DdOPAA 2026 - School Master List
-- Source: Schools_List.xlsx
-- Municipality and School District are intentionally left NULL.
-- Authorized users will assign/update them later in PMMS.
-- MySQL 8+

START TRANSACTION;

-- Assumes existing table: schools
-- Expected columns: school_id, name, type, municipality_id, school_district_id, created_at, updated_at
-- Existing municipality/district assignments are preserved on duplicate school_id.

INSERT INTO `schools` (`school_id`, `name`, `type`, `municipality_id`, `school_district_id`, `created_at`, `updated_at`) VALUES
(464059, 'A.G.L. Montevista Baptist Christian Academy, Inc.', 'Private', NULL, NULL, NOW(), NOW()),
(410357, 'Academia De Maria Mediatrix, Inc.', 'Private', NULL, NULL, NOW(), NOW()),
(405331, 'Agape Christian Academy of Monkayo', 'Private', NULL, NULL, NOW(), NOW()),
(501053, 'Alimadmad Integrated School', 'Public', NULL, NULL, NOW(), NOW()),
(137006, 'Amogad Elementary School', 'Public', NULL, NULL, NOW(), NOW()),
(128279, 'Amorcruz ES', 'Public', NULL, NULL, NOW(), NOW()),
(501912, 'Anagase Integrated School', 'Public', NULL, NULL, NOW(), NOW()),
(128510, 'Andap ES', 'Public', NULL, NULL, NOW(), NOW()),
(128280, 'Andap ES', 'Public', NULL, NULL, NOW(), NOW()),
(315814, 'Andap NHS', 'Public', NULL, NULL, NOW(), NOW()),
(128405, 'Andili ES', 'Public', NULL, NULL, NOW(), NOW()),
(304172, 'Andili NHS', 'Public', NULL, NULL, NOW(), NOW()),
(128344, 'Anibongan ES', 'Public', NULL, NULL, NOW(), NOW()),
(304173, 'Anibongan NHS', 'Public', NULL, NULL, NOW(), NOW()),
(128363, 'Anislagan ES', 'Public', NULL, NULL, NOW(), NOW()),
(128480, 'Anislagan ES', 'Public', NULL, NULL, NOW(), NOW()),
(128281, 'Anitap ES', 'Public', NULL, NULL, NOW(), NOW()),
(128328, 'Anitapan ES', 'Public', NULL, NULL, NOW(), NOW()),
(304174, 'Anitapan NHS', 'Public', NULL, NULL, NOW(), NOW()),
(502373, 'Antequera Integrated School', 'Public', NULL, NULL, NOW(), NOW()),
(128532, 'Araibo ES', 'Public', NULL, NULL, NOW(), NOW()),
(304175, 'Araibo NHS', 'Public', NULL, NULL, NOW(), NOW()),
(405320, 'Assumption Academy of Compostela', 'Private', NULL, NULL, NOW(), NOW()),
(405328, 'Assumption Academy of Mawab, Inc.', 'Private', NULL, NULL, NOW(), NOW()),
(405332, 'Assumption Academy of Monkayo, Inc.', 'Private', NULL, NULL, NOW(), NOW()),
(405335, 'Assumption College of Nabunturan', 'Private', NULL, NULL, NOW(), NOW()),
(304193, 'Atty. Orlando S. Rimando NHS', 'Public', NULL, NULL, NOW(), NOW()),
(128259, 'Aurora ES', 'Public', NULL, NULL, NOW(), NOW()),
(128424, 'Awao ES', 'Public', NULL, NULL, NOW(), NOW()),
(304200, 'Awao NHS', 'Public', NULL, NULL, NOW(), NOW()),
(128534, 'Ayan ES', 'Public', NULL, NULL, NOW(), NOW()),
(128425, 'Babag ES', 'Public', NULL, NULL, NOW(), NOW()),
(304176, 'Babag NHS', 'Public', NULL, NULL, NOW(), NOW()),
(128282, 'Bagong Silang ES', 'Public', NULL, NULL, NOW(), NOW()),
(128378, 'Bagong Silang ES', 'Public', NULL, NULL, NOW(), NOW()),
(300577, 'Bagong Silang National High School', 'Public', NULL, NULL, NOW(), NOW()),
(128426, 'Bagong Taas ES', 'Public', NULL, NULL, NOW(), NOW()),
(128260, 'Bagongon ES', 'Public', NULL, NULL, NOW(), NOW()),
(128379, 'Bahi ES', 'Public', NULL, NULL, NOW(), NOW()),
(305771, 'Bahi National High School', 'Public', NULL, NULL, NOW(), NOW()),
(128459, 'Banagbanag ES', 'Public', NULL, NULL, NOW(), NOW()),
(128283, 'Banbanon ES', 'Public', NULL, NULL, NOW(), NOW()),
(128460, 'Banglasan ES', 'Public', NULL, NULL, NOW(), NOW()),
(128261, 'Bango ES', 'Public', NULL, NULL, NOW(), NOW()),
(315819, 'Bango NHS', 'Public', NULL, NULL, NOW(), NOW()),
(128461, 'Bankerohan ES', 'Public', NULL, NULL, NOW(), NOW()),
(204007, 'Bankerohan Sur ES', 'Public', NULL, NULL, NOW(), NOW()),
(128427, 'Banlag ES', 'Public', NULL, NULL, NOW(), NOW()),
(128511, 'Bantacan ES', 'Public', NULL, NULL, NOW(), NOW()),
(304177, 'Bantacan NHS', 'Public', NULL, NULL, NOW(), NOW()),
(128512, 'Barabat ES', 'Public', NULL, NULL, NOW(), NOW()),
(137397, 'Barez Elementary School', 'Public', NULL, NULL, NOW(), NOW()),
(128284, 'Barubo ES', 'Public', NULL, NULL, NOW(), NOW()),
(501365, 'Basak Integrated School', 'Public', NULL, NULL, NOW(), NOW()),
(128513, 'Batinao ES', 'Public', NULL, NULL, NOW(), NOW()),
(128406, 'Bawani ES', 'Public', NULL, NULL, NOW(), NOW()),
(128501, 'Bayabas ES', 'Public', NULL, NULL, NOW(), NOW()),
(304178, 'Bayabas NHS', 'Public', NULL, NULL, NOW(), NOW()),
(128285, 'Bayanihan ES', 'Public', NULL, NULL, NOW(), NOW()),
(128428, 'Baylo ES', 'Public', NULL, NULL, NOW(), NOW()),
(501368, 'Belmonte Integrated School', 'Public', NULL, NULL, NOW(), NOW()),
(128536, 'Biasong ES', 'Public', NULL, NULL, NOW(), NOW()),
(128287, 'Binasbas ES', 'Public', NULL, NULL, NOW(), NOW()),
(128537, 'Binogsayan ES', 'Public', NULL, NULL, NOW(), NOW()),
(409422, 'Bishop Joemar M. Soriano Academy of Comval, Inc.', 'Private', NULL, NULL, NOW(), NOW()),
(128440, 'Bliss ES', 'Public', NULL, NULL, NOW(), NOW()),
(128429, 'Boay ES', 'Public', NULL, NULL, NOW(), NOW()),
(128535, 'Bon-Temple ES', 'Public', NULL, NULL, NOW(), NOW()),
(128538, 'Bongabong ES', 'Public', NULL, NULL, NOW(), NOW()),
(304179, 'Bongabong NHS', 'Public', NULL, NULL, NOW(), NOW()),
(128539, 'Bongbong ES', 'Public', NULL, NULL, NOW(), NOW()),
(501054, 'Bongkilaton Integrated School', 'Public', NULL, NULL, NOW(), NOW()),
(128540, 'Boringot ES', 'Public', NULL, NULL, NOW(), NOW()),
(300588, 'Boringot National High School', 'Public', NULL, NULL, NOW(), NOW()),
(128345, 'Bucana ES', 'Public', NULL, NULL, NOW(), NOW()),
(128288, 'Buhi ES', 'Public', NULL, NULL, NOW(), NOW()),
(128484, 'Bukal ES', 'Public', NULL, NULL, NOW(), NOW()),
(128289, 'Bullokan ES', 'Public', NULL, NULL, NOW(), NOW()),
(128507, 'C.M. Recto ES', 'Public', NULL, NULL, NOW(), NOW()),
(128485, 'Cabacungan ES', 'Public', NULL, NULL, NOW(), NOW()),
(204019, 'Cabanggatan ES', 'Public', NULL, NULL, NOW(), NOW()),
(501778, 'Cabangkalan Integrated School', 'Public', NULL, NULL, NOW(), NOW()),
(128486, 'Cabidianan ES', 'Public', NULL, NULL, NOW(), NOW()),
(300607, 'Cabidianan National High School', 'Public', NULL, NULL, NOW(), NOW()),
(128514, 'Cabinuangan CES', 'Public', NULL, NULL, NOW(), NOW()),
(128329, 'Cabuyoan ES', 'Public', NULL, NULL, NOW(), NOW()),
(128330, 'Cadunan ES', 'Public', NULL, NULL, NOW(), NOW()),
(300608, 'Cagan National High School', 'Public', NULL, NULL, NOW(), NOW()),
(128364, 'Calabcab ES', 'Public', NULL, NULL, NOW(), NOW()),
(137015, 'Calinogan Elementary School', 'Public', NULL, NULL, NOW(), NOW()),
(128515, 'Camanlangan ES', 'Public', NULL, NULL, NOW(), NOW()),
(304180, 'Camanlangan NHS', 'Public', NULL, NULL, NOW(), NOW()),
(128462, 'Camansi ES', 'Public', NULL, NULL, NOW(), NOW()),
(300640, 'Camansi National High School', 'Public', NULL, NULL, NOW(), NOW()),
(128463, 'Camantangan ES', 'Public', NULL, NULL, NOW(), NOW()),
(128380, 'Cambagang ES', 'Public', NULL, NULL, NOW(), NOW()),
(128290, 'Candiis ES', 'Public', NULL, NULL, NOW(), NOW()),
(128331, 'Candinuyan ES', 'Public', NULL, NULL, NOW(), NOW()),
(501055, 'Canidkid Integrated School', 'Public', NULL, NULL, NOW(), NOW()),
(128381, 'Caragan ES', 'Public', NULL, NULL, NOW(), NOW()),
(405333, 'Casa Amazing Grace School, Inc.', 'Private', NULL, NULL, NOW(), NOW()),
(464001, 'Casa Amazing Grade School, Inc. - Mt. Diwata Branch', 'Private', NULL, NULL, NOW(), NOW()),
(128431, 'Casoon ES', 'Public', NULL, NULL, NOW(), NOW()),
(315801, 'Casoon NHS', 'Public', NULL, NULL, NOW(), NOW()),
(128291, 'Ceboleda ES', 'Public', NULL, NULL, NOW(), NOW()),
(464052, 'Christ Centered Christian Baptist Academy, Inc.', 'Private', NULL, NULL, NOW(), NOW()),
(501056, 'Cogonon Integrated School', 'Public', NULL, NULL, NOW(), NOW()),
(128263, 'Compostela Central Elementary School SPED Center', 'Public', NULL, NULL, NOW(), NOW()),
(405321, 'Compostela Christian School, Inc.', 'Private', NULL, NULL, NOW(), NOW()),
(304181, 'Compostela NHS', 'Public', NULL, NULL, NOW(), NOW()),
(403727, 'Compostela Valley Institute of Technology (COMVIT), Inc.', 'Private', NULL, NULL, NOW(), NOW()),
(411665, 'Compostela, Davao de Oro Fundamental Baptist Learning Academy, Inc.', 'Private', NULL, NULL, NOW(), NOW()),
(405337, 'Comval Christian Academy', 'Private', NULL, NULL, NOW(), NOW()),
(128346, 'Concepcion ES', 'Public', NULL, NULL, NOW(), NOW()),
(128407, 'Concepcion ES', 'Public', NULL, NULL, NOW(), NOW()),
(502197, 'Concepcion Integrated School', 'Public', NULL, NULL, NOW(), NOW()),
(304184, 'Consuelo M. Valderrama NHS', 'Public', NULL, NULL, NOW(), NOW()),
(405324, 'Cor Jesu Institute of Mabini, Inc.', 'Private', NULL, NULL, NOW(), NOW()),
(204020, 'Corazon C. Aquino ES', 'Public', NULL, NULL, NOW(), NOW()),
(315820, 'Corazon C. Aquino NHS', 'Public', NULL, NULL, NOW(), NOW()),
(409610, 'Corban Learnin Center, Inc.', 'Private', NULL, NULL, NOW(), NOW()),
(501774, 'Coronobe Integrated School', 'Public', NULL, NULL, NOW(), NOW()),
(204016, 'Dalimdim ES', 'Public', NULL, NULL, NOW(), NOW()),
(501652, 'Danggayon Integrated School', 'Public', NULL, NULL, NOW(), NOW()),
(128293, 'Datu Ampunan ES', 'Public', NULL, NULL, NOW(), NOW()),
(128294, 'Datu Davao ES', 'Public', NULL, NULL, NOW(), NOW()),
(305775, 'Datu Davao National High School', 'Public', NULL, NULL, NOW(), NOW()),
(128465, 'Dauman ES', 'Public', NULL, NULL, NOW(), NOW()),
(128332, 'Del Pilar ES', 'Public', NULL, NULL, NOW(), NOW()),
(204010, 'Depot ES', 'Public', NULL, NULL, NOW(), NOW()),
(300667, 'Depot Ancestral Domain National High School', 'Public', NULL, NULL, NOW(), NOW()),
(128541, 'Diat ES', 'Public', NULL, NULL, NOW(), NOW()),
(204001, 'Diosdado Macapagal ES', 'Public', NULL, NULL, NOW(), NOW()),
(300927, 'Diosdado Macapagal National High School', 'Public', NULL, NULL, NOW(), NOW()),
(304185, 'Don Vicente Romualdez NHS', 'Public', NULL, NULL, NOW(), NOW()),
(128333, 'Don William Gemperle ES', 'Public', NULL, NULL, NOW(), NOW()),
(128295, 'Doña Josefa ES', 'Public', NULL, NULL, NOW(), NOW()),
(128542, 'Doroteo De Castro ES', 'Public', NULL, NULL, NOW(), NOW()),
(128365, 'Dumlan ES', 'Public', NULL, NULL, NOW(), NOW()),
(128533, 'Eduardo H. Maquidato, Sr. ES', 'Public', NULL, NULL, NOW(), NOW()),
(128296, 'El Katipunan ES', 'Public', NULL, NULL, NOW(), NOW()),
(128347, 'Elizalde ES', 'Public', NULL, NULL, NOW(), NOW()),
(304186, 'Elizalde National High School', 'Public', NULL, NULL, NOW(), NOW()),
(137348, 'Florencio M. Guay Elementary School', 'Public', NULL, NULL, NOW(), NOW()),
(411666, 'Fundamental Baptist Christian Academy of Mawab-Comval, Inc.', 'Private', NULL, NULL, NOW(), NOW()),
(128264, 'Gabi ES', 'Public', NULL, NULL, NOW(), NOW()),
(304187, 'Gabi National High School', 'Public', NULL, NULL, NOW(), NOW()),
(128348, 'Gayab ES', 'Public', NULL, NULL, NOW(), NOW()),
(315822, 'Golden Valley NHS', 'Public', NULL, NULL, NOW(), NOW()),
(137317, 'Gov. Vicente G. Duterte Elementary School', 'Public', NULL, NULL, NOW(), NOW()),
(128349, 'Gubatan ES', 'Public', NULL, NULL, NOW(), NOW()),
(128408, 'Guisok ES', 'Public', NULL, NULL, NOW(), NOW()),
(501367, 'Gumayan Integrated School', 'Public', NULL, NULL, NOW(), NOW()),
(128432, 'Haguimitan ES', 'Public', NULL, NULL, NOW(), NOW()),
(411657, 'High Ram Academe, Inc.', 'Private', NULL, NULL, NOW(), NOW()),
(128350, 'Hijo ES', 'Public', NULL, NULL, NOW(), NOW()),
(128297, 'Hinagtungan ES', 'Public', NULL, NULL, NOW(), NOW()),
(128298, 'Ilpapa ES', 'Public', NULL, NULL, NOW(), NOW()),
(128299, 'Imelda ES', 'Public', NULL, NULL, NOW(), NOW()),
(128300, 'Inakayan ES', 'Public', NULL, NULL, NOW(), NOW()),
(128433, 'Inambatan ES', 'Public', NULL, NULL, NOW(), NOW()),
(137067, 'Inopawan Elementary School', 'Public', NULL, NULL, NOW(), NOW()),
(405329, 'Institution of Northern Davao, Inc.', 'Private', NULL, NULL, NOW(), NOW()),
(410741, 'Interface Technological College of Davao De Oro, Inc.', 'Private', NULL, NULL, NOW(), NOW()),
(410743, 'Interface Technological College of Davao Region, Inc.', 'Private', NULL, NULL, NOW(), NOW()),
(128366, 'Kaburakanan ES', 'Public', NULL, NULL, NOW(), NOW()),
(501770, 'Kaligutan Integrated School', 'Public', NULL, NULL, NOW(), NOW()),
(204004, 'Kaluyapi ES', 'Public', NULL, NULL, NOW(), NOW()),
(128487, 'Kao ES', 'Public', NULL, NULL, NOW(), NOW()),
(315806, 'Kao NHS', 'Public', NULL, NULL, NOW(), NOW()),
(128302, 'Kapatagan ES', 'Public', NULL, NULL, NOW(), NOW()),
(304188, 'Kapatagan National High School', 'Public', NULL, NULL, NOW(), NOW()),
(204013, 'Kapoc ES', 'Public', NULL, NULL, NOW(), NOW()),
(131139, 'Katipunan ES', 'Public', NULL, NULL, NOW(), NOW()),
(128409, 'Katipunan ES', 'Public', NULL, NULL, NOW(), NOW()),
(128517, 'Katipunan ES', 'Public', NULL, NULL, NOW(), NOW()),
(128488, 'Katipunan ES', 'Public', NULL, NULL, NOW(), NOW()),
(501769, 'Katipunan Integrated School', 'Public', NULL, NULL, NOW(), NOW()),
(128303, 'Kibaguio ES', 'Public', NULL, NULL, NOW(), NOW()),
(128304, 'Kidawa ES', 'Public', NULL, NULL, NOW(), NOW()),
(304190, 'Kidawa NHS', 'Public', NULL, NULL, NOW(), NOW()),
(128305, 'Kilagdeng ES', 'Public', NULL, NULL, NOW(), NOW()),
(305774, 'Kilagding National High School', 'Public', NULL, NULL, NOW(), NOW()),
(137435, 'Kinabuhian Elementary School', 'Public', NULL, NULL, NOW(), NOW()),
(128544, 'Kingking CES', 'Public', NULL, NULL, NOW(), NOW()),
(128351, 'Kinuban ES', 'Public', NULL, NULL, NOW(), NOW()),
(128306, 'Kiokmay ES', 'Public', NULL, NULL, NOW(), NOW()),
(128307, 'L.S. Sarmiento ES', 'Public', NULL, NULL, NOW(), NOW()),
(411271, 'La Escuela Global Academy of Davao de Oro, Inc.', 'Private', NULL, NULL, NOW(), NOW()),
(128518, 'La Purisima ES', 'Public', NULL, NULL, NOW(), NOW()),
(128308, 'Laak CES', 'Public', NULL, NULL, NOW(), NOW()),
(464005, 'Laak Institute Foundation, Inc.', 'Private', NULL, NULL, NOW(), NOW()),
(304189, 'Laak NHS', 'Public', NULL, NULL, NOW(), NOW()),
(128265, 'Lagab ES', 'Public', NULL, NULL, NOW(), NOW()),
(128384, 'Lahi ES', 'Public', NULL, NULL, NOW(), NOW()),
(128545, 'Lahi ES', 'Public', NULL, NULL, NOW(), NOW()),
(204003, 'Langgam ES', 'Public', NULL, NULL, NOW(), NOW()),
(315813, 'Langgawisan NHS', 'Public', NULL, NULL, NOW(), NOW()),
(128309, 'Langtud ES', 'Public', NULL, NULL, NOW(), NOW()),
(128352, 'Lapulapu ES', 'Public', NULL, NULL, NOW(), NOW()),
(128546, 'Las Arenas ES', 'Public', NULL, NULL, NOW(), NOW()),
(301052, 'Lawaan National High School', 'Public', NULL, NULL, NOW(), NOW()),
(464031, 'Legacy College of Compostela, Inc.', 'Private', NULL, NULL, NOW(), NOW()),
(405325, 'Letran de Davao of Maco, Inc.', 'Private', NULL, NULL, NOW(), NOW()),
(128489, 'Libasan ES', 'Public', NULL, NULL, NOW(), NOW()),
(301294, 'Libaylibay NHS', 'Public', NULL, NULL, NOW(), NOW()),
(128334, 'Libudon ES', 'Public', NULL, NULL, NOW(), NOW()),
(128310, 'Libuton ES', 'Public', NULL, NULL, NOW(), NOW()),
(128368, 'Limbo ES', 'Public', NULL, NULL, NOW(), NOW()),
(204022, 'Limot ES', 'Public', NULL, NULL, NOW(), NOW()),
(502242, 'Linda Integrated School', 'Public', NULL, NULL, NOW(), NOW()),
(128547, 'Liniputan ES', 'Public', NULL, NULL, NOW(), NOW()),
(128466, 'Linoan ES', 'Public', NULL, NULL, NOW(), NOW()),
(128434, 'Liwanag ES', 'Public', NULL, NULL, NOW(), NOW()),
(501779, 'Longanapan Integrated School', 'Public', NULL, NULL, NOW(), NOW()),
(128410, 'Lonolono ES', 'Public', NULL, NULL, NOW(), NOW()),
(304191, 'Lorenzo S. Sarmiento Sr. NHS', 'Public', NULL, NULL, NOW(), NOW()),
(128312, 'Lower Ampawid ES', 'Public', NULL, NULL, NOW(), NOW()),
(204008, 'Lower Panansalan ES', 'Public', NULL, NULL, NOW(), NOW()),
(204006, 'Lumatab ES', 'Public', NULL, NULL, NOW(), NOW()),
(128467, 'Mabanda ES', 'Public', NULL, NULL, NOW(), NOW()),
(128335, 'Mabini CES', 'Public', NULL, NULL, NOW(), NOW()),
(304192, 'Mabini NHS', 'Public', NULL, NULL, NOW(), NOW()),
(128387, 'Mabugnao ES', 'Public', NULL, NULL, NOW(), NOW()),
(128313, 'Mabuhay ES', 'Public', NULL, NULL, NOW(), NOW()),
(128435, 'Mabuhay ES', 'Public', NULL, NULL, NOW(), NOW()),
(301358, 'Mabuhay National High School', 'Public', NULL, NULL, NOW(), NOW()),
(128353, 'Maco CES', 'Public', NULL, NULL, NOW(), NOW()),
(464011, 'Maco Christian Learning Center', 'Private', NULL, NULL, NOW(), NOW()),
(128369, 'Maco Heights CES', 'Public', NULL, NULL, NOW(), NOW()),
(128436, 'Macopa ES', 'Public', NULL, NULL, NOW(), NOW()),
(128490, 'Magading ES', 'Public', NULL, NULL, NOW(), NOW()),
(128354, 'Magangit ES', 'Public', NULL, NULL, NOW(), NOW()),
(501057, 'Magangit Integrated School', 'Public', NULL, NULL, NOW(), NOW()),
(128385, 'Magcagong ES', 'Public', NULL, NULL, NOW(), NOW()),
(305778, 'Magcagong National High School', 'Public', NULL, NULL, NOW(), NOW()),
(128548, 'Magnaga Elementary School', 'Public', NULL, NULL, NOW(), NOW()),
(315807, 'Magnaga National High School', 'Public', NULL, NULL, NOW(), NOW()),
(128503, 'Magsaysay ES', 'Public', NULL, NULL, NOW(), NOW()),
(128520, 'Magsaysay ES', 'Public', NULL, NULL, NOW(), NOW()),
(315821, 'Magsaysay NHS', 'Public', NULL, NULL, NOW(), NOW()),
(128468, 'Magtaya ES', 'Public', NULL, NULL, NOW(), NOW()),
(128411, 'Mahayag ES', 'Public', NULL, NULL, NOW(), NOW()),
(128386, 'Mahayahay ES', 'Public', NULL, NULL, NOW(), NOW()),
(128491, 'Mainit ES', 'Public', NULL, NULL, NOW(), NOW()),
(304194, 'Mainit NHS', 'Public', NULL, NULL, NOW(), NOW()),
(305773, 'Major Angel V. Fajardo National High School', 'Public', NULL, NULL, NOW(), NOW()),
(128314, 'Makopa ES', 'Public', NULL, NULL, NOW(), NOW()),
(128315, 'Malinao ES', 'Public', NULL, NULL, NOW(), NOW()),
(128412, 'Malinawon ES', 'Public', NULL, NULL, NOW(), NOW()),
(128336, 'Mambatang ES', 'Public', NULL, NULL, NOW(), NOW()),
(128266, 'Mambusao ES', 'Public', NULL, NULL, NOW(), NOW()),
(128437, 'Mamonga ES', 'Public', NULL, NULL, NOW(), NOW()),
(128337, 'Manasa ES', 'Public', NULL, NULL, NOW(), NOW()),
(128492, 'Manat CES', 'Public', NULL, NULL, NOW(), NOW()),
(304195, 'Manat NHS', 'Public', NULL, NULL, NOW(), NOW()),
(128267, 'Mangayon ES', 'Public', NULL, NULL, NOW(), NOW()),
(304182, 'Mangayon NHS', 'Public', NULL, NULL, NOW(), NOW()),
(128316, 'Mangloy ES', 'Public', NULL, NULL, NOW(), NOW()),
(306038, 'Mangloy National High School', 'Public', NULL, NULL, NOW(), NOW()),
(128370, 'Manipongol ES', 'Public', NULL, NULL, NOW(), NOW()),
(137005, 'Mansinao-An Elementary School', 'Public', NULL, NULL, NOW(), NOW()),
(500533, 'Manurigao Integrated School', 'Public', NULL, NULL, NOW(), NOW()),
(128371, 'Mapaang ES', 'Public', NULL, NULL, NOW(), NOW()),
(502912, 'Mapaca Integrated School', 'Public', NULL, NULL, NOW(), NOW()),
(128269, 'Maparat ES', 'Public', NULL, NULL, NOW(), NOW()),
(304196, 'Maparat NHS', 'Public', NULL, NULL, NOW(), NOW()),
(128522, 'Mapaso ES', 'Public', NULL, NULL, NOW(), NOW()),
(128388, 'Mapawa Central Elementary School', 'Public', NULL, NULL, NOW(), NOW()),
(304197, 'Mapawa NHS', 'Public', NULL, NULL, NOW(), NOW()),
(128389, 'Maragusan CES', 'Public', NULL, NULL, NOW(), NOW()),
(304198, 'Maragusan NHS', 'Public', NULL, NULL, NOW(), NOW()),
(464022, 'Maragusan Seventh Day Adventist Learning Center, Inc.', 'Private', NULL, NULL, NOW(), NOW()),
(464054, 'Maranatha Bible Baptist Academy of Compostela Valley, Inc.', 'Private', NULL, NULL, NOW(), NOW()),
(128338, 'Masicareg ES', 'Public', NULL, NULL, NOW(), NOW()),
(128493, 'Matagdungan ES', 'Public', NULL, NULL, NOW(), NOW()),
(128438, 'Matangad ES', 'Public', NULL, NULL, NOW(), NOW()),
(128549, 'Matiao ES', 'Public', NULL, NULL, NOW(), NOW()),
(128494, 'Matilo ES', 'Public', NULL, NULL, NOW(), NOW()),
(128550, 'Maubog ES', 'Public', NULL, NULL, NOW(), NOW()),
(204021, 'Maugat ES', 'Public', NULL, NULL, NOW(), NOW()),
(128390, 'Mauswagon ES', 'Public', NULL, NULL, NOW(), NOW()),
(128413, 'Mawab Central Elementary School SPED Center', 'Public', NULL, NULL, NOW(), NOW()),
(128469, 'Mayaon ES', 'Public', NULL, NULL, NOW(), NOW()),
(304204, 'Mayaon NHS', 'Public', NULL, NULL, NOW(), NOW()),
(128470, 'Mayobe ES', 'Public', NULL, NULL, NOW(), NOW()),
(128317, 'Melale ES', 'Public', NULL, NULL, NOW(), NOW()),
(315804, 'Melale NHS', 'Public', NULL, NULL, NOW(), NOW()),
(128504, 'Mipangi ES', 'Public', NULL, NULL, NOW(), NOW()),
(128439, 'Monkayo CES', 'Public', NULL, NULL, NOW(), NOW()),
(304199, 'Monkayo NHS', 'Public', NULL, NULL, NOW(), NOW()),
(128471, 'Montevista CES', 'Public', NULL, NULL, NOW(), NOW()),
(304202, 'Montevista NHS', 'Public', NULL, NULL, NOW(), NOW()),
(304203, 'Montevista Stand Alone Senior High School', 'Public', NULL, NULL, NOW(), NOW()),
(128441, 'Moria ES', 'Public', NULL, NULL, NOW(), NOW()),
(128442, 'Mt. Diwata ES', 'Public', NULL, NULL, NOW(), NOW()),
(128444, 'Naboc ES', 'Public', NULL, NULL, NOW(), NOW()),
(464029, 'Nabunturan Central Baptist Academy', 'Private', NULL, NULL, NOW(), NOW()),
(128505, 'Nabunturan Central Elementary School SPED Center', 'Public', NULL, NULL, NOW(), NOW()),
(304205, 'Nabunturan NCHS', 'Public', NULL, NULL, NOW(), NOW()),
(128318, 'Naga ES', 'Public', NULL, NULL, NOW(), NOW()),
(128551, 'Nagas ES', 'Public', NULL, NULL, NOW(), NOW()),
(128552, 'Napnapan ES', 'Public', NULL, NULL, NOW(), NOW()),
(315816, 'Napnapan NHS', 'Public', NULL, NULL, NOW(), NOW()),
(411310, 'NCBA Grade School of Davao de Oro, Inc.', 'Private', NULL, NULL, NOW(), NOW()),
(409219, 'Nestor Fausta Memorial College', 'Private', NULL, NULL, NOW(), NOW()),
(128391, 'New Albay ES', 'Public', NULL, NULL, NOW(), NOW()),
(315815, 'New Albay NHS', 'Public', NULL, NULL, NOW(), NOW()),
(128270, 'New Alegria ES', 'Public', NULL, NULL, NOW(), NOW()),
(128355, 'New Asturias ES', 'Public', NULL, NULL, NOW(), NOW()),
(128356, 'New Barili ES', 'Public', NULL, NULL, NOW(), NOW()),
(304206, 'New Bataan NHS', 'Public', NULL, NULL, NOW(), NOW()),
(128319, 'New Bethlehem ES', 'Public', NULL, NULL, NOW(), NOW()),
(128472, 'New Calape ES', 'Public', NULL, NULL, NOW(), NOW()),
(128473, 'New Dalaguete ES', 'Public', NULL, NULL, NOW(), NOW()),
(128495, 'New Dauis ES', 'Public', NULL, NULL, NOW(), NOW()),
(128445, 'New Kapatagan ES', 'Public', NULL, NULL, NOW(), NOW()),
(315823, 'New Kapatagan NHS', 'Public', NULL, NULL, NOW(), NOW()),
(128392, 'New Katipunan ES', 'Public', NULL, NULL, NOW(), NOW()),
(128373, 'New Leyte ES', 'Public', NULL, NULL, NOW(), NOW()),
(315811, 'New Leyte NHS', 'Public', NULL, NULL, NOW(), NOW()),
(128393, 'New Manay ES', 'Public', NULL, NULL, NOW(), NOW()),
(128394, 'New Negros ES', 'Public', NULL, NULL, NOW(), NOW()),
(501771, 'New Panay Integrated School', 'Public', NULL, NULL, NOW(), NOW()),
(128506, 'New Sibonga ES', 'Public', NULL, NULL, NOW(), NOW()),
(315818, 'New Sibonga NHS', 'Public', NULL, NULL, NOW(), NOW()),
(128357, 'New Visayas ES', 'Public', NULL, NULL, NOW(), NOW()),
(128474, 'New Visayas ES', 'Public', NULL, NULL, NOW(), NOW()),
(305772, 'New Visayas National High School', 'Public', NULL, NULL, NOW(), NOW()),
(128271, 'Ngan ES', 'Public', NULL, NULL, NOW(), NOW()),
(405339, 'Nueva Estrella Santiago Dulos Academy, Inc.', 'Private', NULL, NULL, NOW(), NOW()),
(128414, 'Nueva Visayas ES', 'Public', NULL, NULL, NOW(), NOW()),
(128415, 'Nuevo Iloco ES', 'Public', NULL, NULL, NOW(), NOW()),
(315802, 'Nuevo Iloco National High School', 'Public', NULL, NULL, NOW(), NOW()),
(128496, 'Ogao ES', 'Public', NULL, NULL, NOW(), NOW()),
(500455, 'Olaycon Integrated School', 'Public', NULL, NULL, NOW(), NOW()),
(128272, 'Osmeña ES', 'Public', NULL, NULL, NOW(), NOW()),
(128553, 'P. Fuentes Sr. ES', 'Public', NULL, NULL, NOW(), NOW()),
(204011, 'Paco ES', 'Public', NULL, NULL, NOW(), NOW()),
(128523, 'Pagsabangan ES', 'Public', NULL, NULL, NOW(), NOW()),
(128524, 'Pagsilaan ES', 'Public', NULL, NULL, NOW(), NOW()),
(128396, 'Paloc ES', 'Public', NULL, NULL, NOW(), NOW()),
(304207, 'Paloc NHS', 'Public', NULL, NULL, NOW(), NOW()),
(501772, 'Pamintaran Integrated School', 'Public', NULL, NULL, NOW(), NOW()),
(128525, 'Panag ES', 'Public', NULL, NULL, NOW(), NOW()),
(128339, 'Panamin ES', 'Public', NULL, NULL, NOW(), NOW()),
(128320, 'Panamoren ES', 'Public', NULL, NULL, NOW(), NOW()),
(128374, 'Panangan ES', 'Public', NULL, NULL, NOW(), NOW()),
(500456, 'Panansalan Integrated School', 'Public', NULL, NULL, NOW(), NOW()),
(128554, 'Panganason ES', 'Public', NULL, NULL, NOW(), NOW()),
(128358, 'Pangi ES', 'Public', NULL, NULL, NOW(), NOW()),
(301526, 'Pangi National High School', 'Public', NULL, NULL, NOW(), NOW()),
(128497, 'Pangutosan ES', 'Public', NULL, NULL, NOW(), NOW()),
(128359, 'Panibasan ES', 'Public', NULL, NULL, NOW(), NOW()),
(301585, 'Panibasan National High School', 'Public', NULL, NULL, NOW(), NOW()),
(128375, 'Panoraon ES', 'Public', NULL, NULL, NOW(), NOW()),
(464028, 'Pantukan Baptist Christian School, Inc.', 'Private', NULL, NULL, NOW(), NOW()),
(128555, 'Pantukan ES', 'Public', NULL, NULL, NOW(), NOW()),
(304208, 'Pantukan NHS', 'Public', NULL, NULL, NOW(), NOW()),
(501768, 'Parasanon Integrated School', 'Public', NULL, NULL, NOW(), NOW()),
(128447, 'Pasian ES', 'Public', NULL, NULL, NOW(), NOW()),
(304201, 'Pasian National High School', 'Public', NULL, NULL, NOW(), NOW()),
(128556, 'Piasusuan ES', 'Public', NULL, NULL, NOW(), NOW()),
(128448, 'Pilar ES', 'Public', NULL, NULL, NOW(), NOW()),
(128340, 'Pindasan ES', 'Public', NULL, NULL, NOW(), NOW()),
(315805, 'Pindasan NHS', 'Public', NULL, NULL, NOW(), NOW()),
(501366, 'Pongpong Integrated School', 'Public', NULL, NULL, NOW(), NOW()),
(128475, 'Prosperidad ES', 'Public', NULL, NULL, NOW(), NOW()),
(128476, 'Prosperidad Tribal ES', 'Public', NULL, NULL, NOW(), NOW()),
(128557, 'Pulang Lupa ES', 'Public', NULL, NULL, NOW(), NOW()),
(136925, 'Puting Bato Elementary School', 'Public', NULL, NULL, NOW(), NOW()),
(128449, 'Rizal Memorial ES', 'Public', NULL, NULL, NOW(), NOW()),
(128321, 'Sabud ES', 'Public', NULL, NULL, NOW(), NOW()),
(464032, 'Sacred Angel Learning center of Pantukan, Inc.', 'Private', NULL, NULL, NOW(), NOW()),
(405327, 'Saint Vincent Academy of Maragusan, Inc.', 'Private', NULL, NULL, NOW(), NOW()),
(128450, 'Salvacion ES', 'Public', NULL, NULL, NOW(), NOW()),
(502371, 'Salvacion Integrated School', 'Public', NULL, NULL, NOW(), NOW()),
(128477, 'Sambayon ES', 'Public', NULL, NULL, NOW(), NOW()),
(128322, 'San Antonio ES', 'Public', NULL, NULL, NOW(), NOW()),
(128341, 'San Antonio ES', 'Public', NULL, NULL, NOW(), NOW()),
(315812, 'San Antonio NHS', 'Public', NULL, NULL, NOW(), NOW()),
(128527, 'San Isidro ES', 'Public', NULL, NULL, NOW(), NOW()),
(501773, 'San Isidro Integrated School', 'Public', NULL, NULL, NOW(), NOW()),
(501776, 'San Isidro Integrated School', 'Public', NULL, NULL, NOW(), NOW()),
(128274, 'San Jose ES', 'Public', NULL, NULL, NOW(), NOW()),
(128452, 'San Jose ES', 'Public', NULL, NULL, NOW(), NOW()),
(128483, 'San Juan ES', 'Public', NULL, NULL, NOW(), NOW()),
(128275, 'San Miguel ES', 'Public', NULL, NULL, NOW(), NOW()),
(304183, 'San Miguel NHS', 'Public', NULL, NULL, NOW(), NOW()),
(137105, 'San Roque Elementary School', 'Public', NULL, NULL, NOW(), NOW()),
(128509, 'San Roque ES', 'Public', NULL, NULL, NOW(), NOW()),
(128528, 'San Roque ES', 'Public', NULL, NULL, NOW(), NOW()),
(128498, 'San Vicente ES', 'Public', NULL, NULL, NOW(), NOW()),
(501058, 'San Vicente Integrated School', 'Public', NULL, NULL, NOW(), NOW()),
(128417, 'San Vicente PS', 'Public', NULL, NULL, NOW(), NOW()),
(128360, 'Sangab ES', 'Public', NULL, NULL, NOW(), NOW()),
(502372, 'Saosao Integrated School', 'Public', NULL, NULL, NOW(), NOW()),
(204009, 'Sapawan ES', 'Public', NULL, NULL, NOW(), NOW()),
(128399, 'Saranga ES', 'Public', NULL, NULL, NOW(), NOW()),
(128558, 'Sarog ES', 'Public', NULL, NULL, NOW(), NOW()),
(204005, 'Sasa ES', 'Public', NULL, NULL, NOW(), NOW()),
(128419, 'Sawangan ES', 'Public', NULL, NULL, NOW(), NOW()),
(128529, 'Simsimen ES', 'Public', NULL, NULL, NOW(), NOW()),
(128361, 'Singanan ES', 'Public', NULL, NULL, NOW(), NOW()),
(128276, 'Siocon ES', 'Public', NULL, NULL, NOW(), NOW()),
(304210, 'Siocon NHS', 'Public', NULL, NULL, NOW(), NOW()),
(128323, 'Sisimon ES', 'Public', NULL, NULL, NOW(), NOW()),
(128324, 'Sta. Emilia ES', 'Public', NULL, NULL, NOW(), NOW()),
(128499, 'Sta. Maria ES', 'Public', NULL, NULL, NOW(), NOW()),
(128559, 'Sta. Teresa ES', 'Public', NULL, NULL, NOW(), NOW()),
(411658, 'Steward Learning Academy, Inc.', 'Private', NULL, NULL, NOW(), NOW()),
(128453, 'Sugod ES', 'Public', NULL, NULL, NOW(), NOW()),
(128277, 'T.H. Valderrama ES', 'Public', NULL, NULL, NOW(), NOW()),
(128420, 'Tabontabon ES', 'Public', NULL, NULL, NOW(), NOW()),
(204012, 'Tadya ES', 'Public', NULL, NULL, NOW(), NOW()),
(204002, 'Tagaytay ES', 'Public', NULL, NULL, NOW(), NOW()),
(128343, 'Tagbalabao ES', 'Public', NULL, NULL, NOW(), NOW()),
(128376, 'Tagbaros ES', 'Public', NULL, NULL, NOW(), NOW()),
(128560, 'Tagdangua ES', 'Public', NULL, NULL, NOW(), NOW()),
(128362, 'Taglawig ES', 'Public', NULL, NULL, NOW(), NOW()),
(128500, 'Tagnocon ES', 'Public', NULL, NULL, NOW(), NOW()),
(128561, 'Tagugpo ES', 'Public', NULL, NULL, NOW(), NOW()),
(304209, 'Tagugpo NHS', 'Public', NULL, NULL, NOW(), NOW()),
(405322, 'Tagum SDA Elementary School, Inc. - Compostela Branch', 'Private', NULL, NULL, NOW(), NOW()),
(405323, 'Tagum SDA Elementary School, Inc. - Laak Branch', 'Private', NULL, NULL, NOW(), NOW()),
(464014, 'Tagum SDA Elementary School, Inc. - Pantukan Branch', 'Private', NULL, NULL, NOW(), NOW()),
(128400, 'Talian ES', 'Public', NULL, NULL, NOW(), NOW()),
(304211, 'Tambongon NHS', 'Public', NULL, NULL, NOW(), NOW()),
(128278, 'Tamia ES', 'Public', NULL, NULL, NOW(), NOW()),
(501780, 'Tan-Awan Integrated School', 'Public', NULL, NULL, NOW(), NOW()),
(501777, 'Tandawan Integrated School', 'Public', NULL, NULL, NOW(), NOW()),
(128401, 'Tandik ES', 'Public', NULL, NULL, NOW(), NOW()),
(128479, 'Tapia ES', 'Public', NULL, NULL, NOW(), NOW()),
(128562, 'Tapis ES', 'Public', NULL, NULL, NOW(), NOW()),
(128531, 'Taytayan ES', 'Public', NULL, NULL, NOW(), NOW()),
(128377, 'Teresa ES', 'Public', NULL, NULL, NOW(), NOW()),
(305637, 'Teresa National High School', 'Public', NULL, NULL, NOW(), NOW()),
(464002, 'The Kiddie Math Science Grade School of Comval, Inc.', 'Private', NULL, NULL, NOW(), NOW()),
(128563, 'Tibagon ES', 'Public', NULL, NULL, NOW(), NOW()),
(128325, 'Tigasa ES', 'Public', NULL, NULL, NOW(), NOW()),
(501775, 'Tigbao Integrated School', 'Public', NULL, NULL, NOW(), NOW()),
(128454, 'Totoy ES', 'Public', NULL, NULL, NOW(), NOW()),
(128455, 'Tubo-Tubo ES', 'Public', NULL, NULL, NOW(), NOW()),
(304212, 'Tubo-Tubo NHS', 'Public', NULL, NULL, NOW(), NOW()),
(128422, 'Tuboran ES', 'Public', NULL, NULL, NOW(), NOW()),
(315803, 'Tuboran National High School', 'Public', NULL, NULL, NOW(), NOW()),
(128403, 'Tuburan ES', 'Public', NULL, NULL, NOW(), NOW()),
(128456, 'Tuburan ES', 'Public', NULL, NULL, NOW(), NOW()),
(137125, 'Tugas Elementary School', 'Public', NULL, NULL, NOW(), NOW()),
(128564, 'Tugop ES', 'Public', NULL, NULL, NOW(), NOW()),
(204014, 'Tugunan ES', 'Public', NULL, NULL, NOW(), NOW()),
(128326, 'Tuk-an ES', 'Public', NULL, NULL, NOW(), NOW()),
(128404, 'Tupas ES', 'Public', NULL, NULL, NOW(), NOW()),
(304213, 'Tupaz NHS', 'Public', NULL, NULL, NOW(), NOW()),
(102234, 'Uduan ES', 'Public', NULL, NULL, NOW(), NOW()),
(128457, 'Ulip ES', 'Public', NULL, NULL, NOW(), NOW()),
(315808, 'Ulip National High School', 'Public', NULL, NULL, NOW(), NOW()),
(128443, 'Union Central Elementary School', 'Public', NULL, NULL, NOW(), NOW()),
(315809, 'Union National High School - Mt. Diwata High School Annex', 'Public', NULL, NULL, NOW(), NOW()),
(304214, 'Union NHS', 'Public', NULL, NULL, NOW(), NOW()),
(204015, 'Upper Camili ES', 'Public', NULL, NULL, NOW(), NOW())

ON DUPLICATE KEY UPDATE
  `name` = VALUES(`name`),
  `type` = VALUES(`type`),
  `updated_at` = NOW();

COMMIT;

-- Imported school records: 461
-- municipality_id and school_district_id remain editable in the application.